USE reviews_samary;

DELETE FROM reviews;
DELETE FROM products;

INSERT INTO products (id, name, description, price) VALUES
(1, 'Dell XPS 15 Laptop', '15.6-inch 3.5K OLED display, Intel Core i7, 16GB RAM, 512GB SSD - premium ultrabook for creators and professionals.', 1899.99),
(2, 'Sony WH-1000XM5 Wireless Headphones', 'Industry-leading noise cancelling over-ear headphones with 30-hour battery life, multipoint Bluetooth, and crystal-clear hands-free calling.', 349.99),
(3, 'Apple iPhone 16 Pro 256GB', '6.3-inch Super Retina XDR display, A18 Pro chip, 48MP Fusion camera system with 4K120 Dolby Vision video, titanium design.', 1099.00),
(4, 'Samsung 65-Inch QLED 4K Smart TV', 'Quantum Dot 4K UHD TV with Dolby Atmos, Motion Xcelerator 120Hz gaming, and built-in smart hub.', 1299.99),
(5, 'Nike Air Zoom Pegasus 41 Running Shoes', 'Responsive foam cushioning and breathable mesh upper - the trusted daily trainer for road runners of every level.', 129.95),
(6, 'Instant Pot Duo 7-in-1 Electric Pressure Cooker (6 Qt)', 'Pressure cooker, slow cooker, rice cooker, steamer, saute pan, yogurt maker, and warmer in one appliance.', 89.99),
(7, 'Canon EOS R50 Mirrorless Camera with RF-S 18-45mm Lens', '24.2MP APS-C sensor, Dual Pixel CMOS AF II with eye detection, and 4K video in a compact creator-friendly body.', 679.00),
(8, 'LG CordZero All-in-One Stick Vacuum', 'Lightweight cordless vacuum with dual power batteries, up to 80 minutes of runtime, and a self-emptying Kompressor dustbin.', 499.99),
(9, 'Kindle Paperwhite 16GB (12th Gen)', '6.8-inch glare-free 300 ppi display, adjustable warm light, weeks of battery life, and IPX8 waterproofing.', 149.99),
(10, 'Herman Miller Aeron Ergonomic Office Chair (Size B)', 'Iconic ergonomic mesh task chair with PostureFit SL back support, fully adjustable arms, and a 12-year warranty.', 1395.00);

INSERT INTO reviews (author, rating, content, createdAt, productId) VALUES
('Sarah Mitchell', 5, 'I am a software developer and this machine handles everything I throw at it. Large codebases compile in seconds, the OLED screen is gorgeous for long editing sessions, and I regularly get eight to nine hours away from the charger. The keyboard and trackpad feel premium, and Windows Hello login is instant. Best Windows laptop I have owned.', '2026-01-18 09:24:00', 1),
('James Okafor', 4, 'Fantastic display and build quality, and it has enough power for 4K video editing in Premiere without stuttering. My only complaints are the fans, which get audible under sustained heavy loads, and the limited port selection that forces me to carry a dongle everywhere. Docked at my desk it is essentially perfect.', '2026-02-02 14:10:00', 1),
('Emily Chen', 5, 'Switched from a MacBook Pro and I am not looking back. The screen is brighter and more colorful, it runs my engineering software like SolidWorks and MATLAB smoothly, and the chassis stays surprisingly cool on my lap. Setup took fifteen minutes and everything just worked, including the fingerprint reader.', '2026-03-21 18:45:00', 1),
('Daniel Reyes', 3, 'The hardware is undeniably beautiful, but mine arrived with noticeable coil whine when the CPU boosts, and the pre-installed bloatware took an evening to clean up. A BIOS update reduced the whine somewhat. When it behaves it is excellent, but for this price I expected better quality control out of the box.', '2026-04-09 11:02:00', 1),
('Amara Johnson', 4, 'As a graduate student this has been a workhorse for two semesters of thesis work, statistical software, and the occasional game. It is light enough to carry across campus daily and the battery survives a full day of lectures. The power brick is chunky, but I mostly charge overnight anyway. Very happy overall.', '2026-05-30 20:33:00', 1);

INSERT INTO reviews (author, rating, content, createdAt, productId) VALUES
('Michael Torres', 5, 'I ride the subway an hour each way and these completely transform the commute. With noise cancelling on, the train rumble fades to almost nothing and I can listen to podcasts at half the volume I used to need. Battery easily lasts a whole week of commutes between charges.', '2026-01-09 08:15:00', 2),
('Hannah Bergstrom', 4, 'Sound quality is warm and detailed, and the app''s equalizer lets me tune it exactly how I like. The noise cancelling is the best I have tested. My one gripe is that unlike the previous model they do not fold up small, so the case takes more room in my bag. Still an easy recommendation.', '2026-02-14 16:40:00', 2),
('Raj Patel', 5, 'I work in an open-plan office and these are a productivity lifesaver. Multipoint pairing lets me stay connected to my laptop and phone at the same time, so calls switch over seamlessly. Colleagues say my voice comes through clearly even when the office is loud, which my old headset never managed.', '2026-03-05 10:55:00', 2),
('Sophie Laurent', 4, 'Wore them for a nine-hour flight to Tokyo and forgot they were on my head. The clamping force is gentle, the ear cups stay cool, and transparency mode is natural enough to hold a conversation with a flight attendant without removing them. Touch controls take a few days to learn but are reliable once you do.', '2026-04-22 07:30:00', 2),
('Chris Nakamura', 3, 'No question the sound and noise cancelling are phenomenal, possibly the best available. However, the connection drops briefly when I walk away from my desk with my phone in a back pocket, and the plastic headband already shows fine scratches after two months. Great headphones with small but real annoyances at this price.', '2026-06-11 19:20:00', 2);

INSERT INTO reviews (author, rating, content, createdAt, productId) VALUES
('Olivia Grant', 5, 'Upgraded from the 13 Pro and the difference is night and day. The camera pulls in far more detail at night, portraits look natural with no weird edge cutouts, and the battery now comfortably lasts from 6 a.m. to midnight with heavy use. The titanium frame makes it feel lighter than it looks.', '2026-01-25 12:05:00', 3),
('Marcus Webb', 4, 'A genuinely excellent phone: the display is stunningly bright outdoors, apps open instantly, and the Action button is more useful than I expected. It loses a star only because the camera bump is so large it rocks on flat surfaces, and honestly the upgrades over last year''s model are incremental.', '2026-02-19 15:50:00', 3),
('Isabella Rossi', 5, 'I shoot short films for social media and the 4K120 Dolby Vision recording is absurd for a phone this size. Combined with a small gimbal it replaces a camera I used to lug around. Color science is consistent between all three lenses, which my old Android could never claim.', '2026-03-30 17:25:00', 3),
('Tom Whitaker', 4, 'Everything about it is top tier - screen, speed, speakers, face unlock - but the price stings, especially with 256GB as the base. It also charges slower than competing flagships. If you are on a two-or-three-year upgrade cycle like me, it is still the safest premium phone to buy.', '2026-05-08 09:40:00', 3),
('Lena Fischer', 3, 'Great phone most of the time, but mine gets uncomfortably hot during demanding gaming sessions while plugged in, and the screen dims itself to cope. Battery health also dropped to 96 percent in six months. Day-to-day performance and the camera are still superb, so I keep it, but the heat management disappoints.', '2026-06-27 21:10:00', 3);

INSERT INTO reviews (author, rating, content, createdAt, productId) VALUES
('Ahmed Hassan', 5, 'Our living room gets a lot of afternoon sun and this is the first TV that stays perfectly watchable at noon. Colors are vivid without looking cartoonish, and motion handling during football is smooth. Hooked up to my PS5 the 120Hz game mode is fantastic with no noticeable input lag at all.', '2026-01-12 18:30:00', 4),
('Karen O''Brien', 4, 'Picture quality is a massive step up from the ten-year-old LED it replaced. Setup took twenty minutes and it walked me through everything. My complaint is the smart platform: it works fine but pushes ads and sponsored content on the home screen, which feels cheap on a premium TV. I mostly use an Apple TV anyway.', '2026-02-25 13:15:00', 4),
('Diego Morales', 5, 'Movie nights have been incredible on this panel. HDR highlights genuinely pop - explosions and sunlit scenes have real intensity - while shadow detail stays visible. Upscaling of old 720p content is surprisingly good too. Wall mounted it with no issues; the slim profile looks elegant in the room.', '2026-04-02 20:05:00', 4),
('Rachel Kim', 3, 'Straight-on the image is beautiful, but seating is a problem: we have a wide sectional and anyone sitting off to the side sees washed-out color. The built-in speakers are also thin and tinny, so budget for a soundbar. Great TV for a narrow room, less ideal for wide seating arrangements.', '2026-05-19 16:45:00', 4),
('Peter Novak', 4, 'Cable TV looks noticeably cleaner than on my old set, streaming apps run quickly, and the remote is simple enough for my parents to use without a manual. It loses a star because only two of the four HDMI ports are the full-spec gaming ones, which matters if you own more than one console.', '2026-07-03 11:35:00', 4);

INSERT INTO reviews (author, rating, content, createdAt, productId) VALUES
('Jessica Alvarez', 5, 'These have carried me through the first two months of marathon training, roughly two hundred miles, and my knees have never felt better. The cushioning absorbs pavement shock without feeling mushy, and the heel lockdown means zero slippage on long runs. Breathability is excellent even in summer humidity.', '2026-02-08 07:10:00', 5),
('Brandon Lee', 4, 'Very comfortable daily trainer with a smooth heel-to-toe transition. Sizing note: they run slightly snug, so I exchanged my usual size for half a size up and the fit is now perfect. After six weeks the midsole still feels responsive, though the outsole rubber is picking up small cuts from rough asphalt.', '2026-03-16 19:55:00', 5),
('Naomi Adeyemi', 5, 'I ran my first 10K race in these and finished without a single blister, which has never happened with a new pair before. They are light enough for tempo days but cushioned enough for easy Sunday miles. The reflective details on the heel are a nice safety touch for my early morning runs.', '2026-04-28 06:40:00', 5),
('Kevin Doyle', 3, 'Comfort is genuinely good and they look great, but durability is a letdown for the price. At around 150 miles the tread pattern on the forefoot is visibly smoothed over and the mesh toe box has started to fray where it meets the sole. Fine for casual joggers; heavy mileage folks should expect to replace them soon.', '2026-06-05 17:20:00', 5),
('Fatima Zahra', 4, 'I have wide feet and these accommodate me better than most neutral trainers, with a roomy toe box that does not squeeze on longer runs. I use them for running three days a week and gym sessions otherwise - stable enough for lifts, breathable enough for classes. Would love more color options in women''s sizes.', '2026-07-21 08:50:00', 5);

INSERT INTO reviews (author, rating, content, createdAt, productId) VALUES
('Laura Bennett', 5, 'As a parent of three this thing has changed weeknight dinners. Chili that took two hours on the stove is done in thirty-five minutes with better flavor, rice comes out perfectly fluffy every time, and the stainless inner pot goes straight in the dishwasher. I use it four or five times a week without exaggeration.', '2026-01-30 18:15:00', 6),
('Steve Kowalski', 4, 'Once you get past the learning curve it is fantastic. My first attempt at pulled pork came out underdone because I did not account for the pressurization time, but the second try was perfect. The sealing ring holds onto strong smells, so I bought a spare ring for sweet dishes like yogurt and cheesecake. Worth every penny.', '2026-03-11 12:45:00', 6),
('Grace Kimani', 5, 'The yogurt function alone justified the purchase - I make two batches a week and it costs a fraction of store-bought. It also handles frozen meat safely, which means I can decide dinner at 6 p.m. without planning ahead. The saute mode browns onions well enough that I rarely dirty a separate pan.', '2026-04-17 15:30:00', 6),
('Miguel Santos', 4, 'Cooks brilliantly and cleanup is genuinely easy, but the six-quart size is right at the limit for a family of five - I would size up to the eight-quart if you cook in bulk. The steam release button is intimidating the first few times until you read that you should use a long utensil and keep your hand clear.', '2026-05-26 19:05:00', 6),
('Diane Foster', 3, 'It works well and the preset buttons are convenient, but the printed manual is nearly useless and the recipe app is cluttered. I learned mostly from online videos. Also, the display only shows time remaining after pressure is reached, which makes estimating dinner timing confusing at first. Solid appliance, mediocre instructions.', '2026-07-08 13:40:00', 6);

INSERT INTO reviews (author, rating, content, createdAt, productId) VALUES
('Alex Turner', 5, 'This was my first real camera after years of phone photography and the difference is stunning. Eye autofocus locks onto my daughter''s face instantly, even when she is running toward me, which means finally getting sharp photos of a toddler who never sits still. The images have depth and color that no phone computes.', '2026-02-20 10:20:00', 7),
('Yuki Tanaka', 4, 'Image quality from the 24MP sensor is excellent and the body is small enough that I actually carry it everywhere, which is the whole point. Two caveats: battery life is modest, so buy a spare, and native RF lenses are pricey compared to older DSLR glass. An adapter solves the lens cost problem nicely.', '2026-03-28 14:55:00', 7),
('Carlos Mendes', 5, 'I bought it for vlogging and it nails everything I need: the flip-out screen faces forward, autofocus follows me reliably while I walk and talk, and 4K video looks crisp straight out of camera with nice skin tones. It is light enough to hold at arm''s length for extended shoots without fatigue.', '2026-05-14 09:10:00', 7),
('Anna Petrova', 4, 'Coming from smartphone photography the learning curve was real, but the automatic modes are smart enough to get good shots on day one while I learned. Low-light performance with the kit lens is average; I added a fast f/1.8 prime and evening photos transformed. The menu system is logical once customized.', '2026-06-22 17:35:00', 7),
('David Osei', 3, 'The camera body and autofocus are genuinely impressive for the price, but the bundled 18-45mm kit lens is the weak link - soft corners and a slow aperture that undersells the sensor. Budget for at least one better lens. Menu diving for video settings can be confusing, though the touchscreen helps.', '2026-08-04 11:25:00', 7);

INSERT INTO reviews (author, rating, content, createdAt, productId) VALUES
('Michelle Park', 5, 'We have a golden retriever and this vacuum handles the constant fur far better than our old upright. The motorized brush bar pulls embedded hair out of the carpet that I did not know was there, and the two batteries mean I can do the whole main floor on one charge cycle. Emptying the bin is genuinely hands-free.', '2026-01-22 16:05:00', 8),
('Roberto Silva', 4, 'Suction power is excellent on both hardwood and carpet, and the auto mode adjusts as you move between surfaces. It is a bit heavier than the stick vacuums I have used before, which matters on stairs and overhead cleaning. Runtime on max power is short, but honestly normal mode picks up nearly everything anyway.', '2026-03-02 10:40:00', 8),
('Jennifer Walsh', 5, 'The self-emptying dock is the feature I did not know I needed - I have not touched dust directly in three months. It compresses debris so the dock bag lasts weeks even with daily quick cleans. It is quiet enough that I can vacuum while the baby naps, which the old canister never allowed.', '2026-04-25 15:15:00', 8),
('Hassan Ali', 3, 'Performance is great but our home is around 2,400 square feet and even with two batteries I cannot finish the whole thing on max power in one session; there is a waiting period for recharge mid-clean. For apartments or targeted daily cleans it would be perfect. For large homes, plan on cleaning in sections.', '2026-06-15 18:50:00', 8),
('Emma Johansson', 4, 'Replaced a five-year-old Dyson and this matches it on suction while being noticeably quieter. The LED headlights on the brush reveal dust under furniture in a way that is both satisfying and horrifying. Build feels solid and the wall mount charges both batteries. The docking mechanism is slightly fiddly, a minor complaint.', '2026-07-29 09:30:00', 8);

INSERT INTO reviews (author, rating, content, createdAt, productId) VALUES
('Nathaniel Brooks', 5, 'I read by the pool most summer evenings and the waterproofing plus the glare-free screen make this perfect for it - sunlight actually improves readability instead of washing it out. The warm light adjustment means no more blue glow ruining my sleep. Weeks between charges is not marketing exaggeration; I charge mine roughly monthly.', '2026-02-05 20:25:00', 9),
('Clara Nguyen', 4, 'My eyes feel dramatically less tired after switching from reading on a tablet. It is light, fits in a coat pocket, and the page response is quick enough that I stopped noticing it. Two wishes: physical page-turn buttons for one-handed reading in bed, and any kind of color for book covers and magazines.', '2026-03-19 21:45:00', 9),
('George Papadopoulos', 5, 'Sixteen gigabytes holds thousands of books, so my entire library travels with me now. The flush-front screen does not trap dust like older models and a quick wipe keeps it spotless. I have dropped it twice on tile, face down, without a scratch. It has genuinely doubled how much I read this year.', '2026-05-02 12:10:00', 9),
('Aisha Mohammed', 5, 'This device cured my late-night doom-scrolling. Because it only does books, I actually fall asleep reading instead of losing an hour to social media. The battery indicator moving once a week still feels like magic. Library integration with Libby works smoothly for borrowing without buying.', '2026-06-20 22:35:00', 9),
('Victor Reyes', 3, 'For novels it is wonderful and I have no complaints about text rendering or comfort. But the black-and-white screen and small size make illustrated PDFs and textbooks cramped and frustrating - images come out gray and washed out. If you mostly read text-based books, buy it; if you read image-heavy documents, look at a larger tablet-style e-reader.', '2026-08-12 14:20:00', 9);

INSERT INTO reviews (author, rating, content, createdAt, productId) VALUES
('Katherine Liu', 5, 'I work from home ten hours a day and had chronic lower back pain for years. Two weeks in the Aeron and the pain is largely gone. The PostureFit support keeps me sitting properly without thinking about it, and the mesh never gets hot like my old foam chair did. Expensive, and worth every cent.', '2026-01-15 11:50:00', 10),
('Martin Keller', 4, 'Build quality is in a different league from sub-five-hundred-dollar chairs - everything is solid, adjustments are precise, and the twelve-year warranty tells you what they expect it to last. Sizing matters: I am average height and Size B fits perfectly, but check the chart before ordering. Only note is that the armrests could adjust a bit further inward.', '2026-03-08 16:30:00', 10),
('Samuel Adeyinka', 5, 'I have owned my first Aeron for ten years with daily use and it looks and functions like new, so when I set up a second home office there was zero hesitation buying another. The mesh has not sagged, the gas cylinder still holds height, and nothing squeaks. Buy once, cry once.', '2026-04-30 13:05:00', 10),
('Diana Volkov', 4, 'Exceptional ergonomic support, especially through long coding sessions - my shoulders and neck stopped tensing up by the end of the day. The suspended mesh seat is brilliant in summer heat. It is a deliberately firm sit, though: if you like curling up cross-legged in your chair, this will not be that chair for you.', '2026-06-10 19:40:00', 10),
('Oliver Bennett', 3, 'The engineering is clearly superb and my posture has improved, but at this price I expected more included - the fully adjustable arms and PostureFit are extras on some configurations, which pushed my cost well past the sticker. Also the hard frame edge digs into my calves when I recline fully. Great chair, complicated pricing.', '2026-08-25 10:15:00', 10);
