import OpenAI from 'openai';
import { llmClient, LLM_MODEL } from './llm.client.ts';

export async function generateSummary(prompt: string): Promise<string> {
   const response = await llmClient.chat.completions.create({
      model: LLM_MODEL,
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.3,
      max_tokens: 400,
   });

   const choice = response.choices[0];
   const msg = choice?.message as
      | (OpenAI.Chat.Completions.ChatCompletionMessage & {
           reasoning?: string;
        })
      | undefined;
   const summary: string = msg?.content || msg?.reasoning || '';

   if (!summary) {
      throw new Error('No summary generated by the AI service');
   }

   return summary.trim();
}
