import 'dotenv/config';
import OpenAI from 'openai';
import { reviewRepository } from '../repositories/review.repository.ts';

export class ReviewService {
   private client: OpenAI;
   private model: string;

   constructor(
      apiKey: string = process.env.GROQ_API_KEY!,
      model: string = 'openai/gpt-oss-20b',
      baseURL: string = 'https://api.groq.com/openai/v1'
   ) {
      this.client = new OpenAI({ apiKey, baseURL });
      this.model = model;
   }

   async summarizeReviews(productId: number): Promise<string> {
      const reviews = await reviewRepository.getReviews(productId, 10);

      if (reviews.length === 0) {
         return 'No reviews available to summarize.';
      }

      const joinedReviews = reviews
         .map((review) => review.content)
         .join('\n\n');

      const prompt = [
         'Summarize the following customer reviews into a single concise paragraph.',
         'Highlight the key pros, the key cons, and the overall sentiment.',
         'Do not mention individual reviewers by name.',
         '',
         'Customer reviews:',
         joinedReviews,
      ].join('\n');

      const response = await this.client.chat.completions.create({
         model: this.model,
         messages: [{ role: 'user', content: prompt }],
         temperature: 0.3,
         max_tokens: 400,
      });

      const choice = response.choices[0];
      const msg = choice?.message as
         | (OpenAI.Chat.Completions.ChatCompletionMessage & {
              reasoning?: string;
           })
         | undefined;
      const summary: string = msg?.content || msg?.reasoning || '';

      if (!summary) {
         throw new Error('No summary generated by the AI service');
      }

      return summary.trim();
   }
}

export const reviewService = new ReviewService();
